/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  ActivityLog: () => import('#controllers/activity_log.controller'),
  Auth: () => import('#controllers/auth.controller'),
  BlogPublic: () => import('#controllers/blog_public.controller'),
  Blog: () => import('#controllers/blog.controller'),
  Dashboard: () => import('#controllers/dashboard.controller'),
  Home: () => import('#controllers/home.controller'),
  Media: () => import('#controllers/media.controller'),
  Permission: () => import('#controllers/permission.controller'),
  Profile: () => import('#controllers/profile.controller'),
  Role: () => import('#controllers/role.controller'),
  User: () => import('#controllers/user.controller'),
  Utils: () => import('#controllers/utils.controller'),
}
