/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type ActivityLogTransformer from '#transformers/activity_log.transformer'
import type BlogVersionTransformer from '#transformers/blog_version.transformer'
import type BlogTransformer from '#transformers/blog.transformer'
import type MediaTransformer from '#transformers/media.transformer'
import type PermissionTransformer from '#transformers/permission.transformer'
import type ProfileTransformer from '#transformers/profile.transformer'
import type RoleTransformer from '#transformers/role.transformer'
import type TagTransformer from '#transformers/tag.transformer'
import type TokenTransformer from '#transformers/token.transformer'
import type UserShortTransformer from '#transformers/user_short.transformer'
import type UserTransformer from '#transformers/user.transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type ActivityLog = InferData<ActivityLogTransformer>
  export namespace ActivityLog {
    export type Variants = InferVariants<ActivityLogTransformer>
  }
  export type BlogVersion = InferData<BlogVersionTransformer>
  export namespace BlogVersion {
    export type Variants = InferVariants<BlogVersionTransformer>
  }
  export type Blog = InferData<BlogTransformer>
  export namespace Blog {
    export type Variants = InferVariants<BlogTransformer>
  }
  export type Media = InferData<MediaTransformer>
  export namespace Media {
    export type Variants = InferVariants<MediaTransformer>
  }
  export type Permission = InferData<PermissionTransformer>
  export namespace Permission {
    export type Variants = InferVariants<PermissionTransformer>
  }
  export type Profile = InferData<ProfileTransformer>
  export namespace Profile {
    export type Variants = InferVariants<ProfileTransformer>
  }
  export type Role = InferData<RoleTransformer>
  export namespace Role {
    export type Variants = InferVariants<RoleTransformer>
  }
  export type Tag = InferData<TagTransformer>
  export namespace Tag {
    export type Variants = InferVariants<TagTransformer>
  }
  export type Token = InferData<TokenTransformer>
  export namespace Token {
    export type Variants = InferVariants<TokenTransformer>
  }
  export type UserShort = InferData<UserShortTransformer>
  export namespace UserShort {
    export type Variants = InferVariants<UserShortTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
