import {
  Alert,
  Button,
  Checkbox,
  Group,
  Paper,
  Stack,
  TagsInput,
  Text,
  TextInput,
  Textarea,
} from '@mantine/core'
import { UseFormReturnType } from '@mantine/form'
import { IconPhoto, IconPhotoPlus, IconTrash, IconUpload } from '@tabler/icons-react'
import type { ChangeEvent, RefObject } from 'react'
import TiptapEditor from '~/components/RTE'
import ImageWithLoader from '~/components/core/image'
import { urlFor } from '~/lib/client'

type BlogFormValues = {
  id: string
  title: string
  is_active: boolean
  is_pinned: boolean
  thumbnail_id: string
  description: string
  tags: string[]
}

type BlogEditorData = {
  id: string
  slug_id: string
}

type Props = {
  data: BlogEditorData | null
  form: UseFormReturnType<BlogFormValues>
  mutationPending: boolean
  isUploadingThumbnail: boolean
  thumbnailPreviewUrl: string
  thumbnailUploadError: string | null
  thumbnailInputRef: RefObject<HTMLInputElement | null>
  tagSuggestions: string[]
  content: Record<string, any>
  editorContentVersion: number
  onContentChange: (value: Record<string, any>) => void
  onOpenMediaLibrary: () => void
  onThumbnailFileChange: (event: ChangeEvent<HTMLInputElement>) => void
  onClearThumbnail: () => void
  formSafeTitle: (value: string) => string
}

export default function BlogEditorTab({
  data,
  form,
  mutationPending,
  isUploadingThumbnail,
  thumbnailPreviewUrl,
  thumbnailUploadError,
  thumbnailInputRef,
  tagSuggestions,
  content,
  editorContentVersion,
  onContentChange,
  onOpenMediaLibrary,
  onThumbnailFileChange,
  onClearThumbnail,
  formSafeTitle,
}: Props) {
  return (
    <Stack>
      {data && <TextInput label="ID" value={form.values.id} readOnly disabled />}

      <TextInput
        withAsterisk
        label="Title"
        placeholder="Blog title"
        value={form.values.title}
        error={form.errors.title}
        disabled={mutationPending}
        onChange={(event) => form.setFieldValue('title', event.target.value)}
      />

      <Group>
        <Checkbox
          label="Active"
          checked={form.values.is_active}
          disabled={mutationPending}
          onChange={(event) => form.setFieldValue('is_active', event.currentTarget.checked)}
        />
        <Checkbox
          label="Pinned"
          checked={form.values.is_pinned}
          disabled={mutationPending}
          onChange={(event) => form.setFieldValue('is_pinned', event.currentTarget.checked)}
        />
      </Group>

      <TextInput
        label="URL Preview"
        value={
          form.values.title
            ? `${formSafeTitle(form.values.title)}-${data?.slug_id || '{slug_id}'}`
            : '{title}-{slug_id}'
        }
        description="Format: {title}-{slug_id}. slug_id is generated by server."
        readOnly
        disabled
      />

      <Stack gap={8}>
        <Text size="sm" fw={500}>
          Thumbnail
        </Text>

        {thumbnailPreviewUrl ? (
          <ImageWithLoader
            src={thumbnailPreviewUrl}
            alt="Blog thumbnail preview"
            radius="md"
            h={220}
            height={220}
            fit="cover"
            fallbackSrc="https://placehold.co/800x400?text=Thumbnail"
          />
        ) : (
          <Paper withBorder radius="md" p="md">
            <Group>
              <IconPhoto size={18} />
              <Text size="sm" c="dimmed">
                No thumbnail selected
              </Text>
            </Group>
          </Paper>
        )}

        <Group>
          <Button
            variant="outline"
            leftSection={<IconPhotoPlus size={16} />}
            disabled={mutationPending || isUploadingThumbnail}
            onClick={onOpenMediaLibrary}
          >
            Select From Library
          </Button>
          <Button
            variant="outline"
            leftSection={<IconUpload size={16} />}
            loading={isUploadingThumbnail}
            disabled={mutationPending}
            onClick={() => thumbnailInputRef.current?.click()}
          >
            Upload Image
          </Button>
          <Button
            variant="light"
            color="red"
            leftSection={<IconTrash size={16} />}
            disabled={mutationPending || (!form.values.thumbnail_id && !thumbnailPreviewUrl)}
            onClick={onClearThumbnail}
          >
            Remove
          </Button>
        </Group>

        <input
          ref={thumbnailInputRef}
          type="file"
          accept="image/*"
          className="hidden"
          onChange={onThumbnailFileChange}
        />

        <TextInput
          label="Selected Thumbnail ID"
          placeholder="No thumbnail selected"
          value={form.values.thumbnail_id}
          readOnly
          disabled
        />

        {thumbnailUploadError ? (
          <Alert color="red" title="Thumbnail Error">
            {thumbnailUploadError}
          </Alert>
        ) : null}
      </Stack>

      <Textarea
        label="Description"
        placeholder="Short blog description"
        value={form.values.description}
        disabled={mutationPending}
        onChange={(event) => form.setFieldValue('description', event.target.value)}
        autosize
        minRows={3}
        maxRows={6}
      />

      <TagsInput
        label="Tags"
        description="Type and press Enter/comma to add tags. "
        placeholder="Type tags..."
        data={tagSuggestions}
        value={form.values.tags}
        splitChars={[',']}
        clearable
        disabled={mutationPending}
        onChange={(value) => form.setFieldValue('tags', value)}
      />

      <div>
        <Text size="sm" fw={500} mb={8}>
          Content
        </Text>
        <TiptapEditor
          key={`blog-editor-content-${editorContentVersion}`}
          content={content}
          onSave={onContentChange}
          getMediaURL={urlFor('api.v1.media.list')}
          uploadMediaURL={urlFor('api.v1.media.upload')}
          deleteMediaURL={urlFor('api.v1.media.destroy')}
          className="min-h-[500px]"
          stickyToolbar={true}
          imageTags={['blog-content']}
        />
      </div>
    </Stack>
  )
}
