/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'

const placeholder: any = {}

const routes = {
  "drive.fs.serve": {
    methods: ["GET"],
    pattern: "/uploads/*",
    tokens: [{"type":0,"val":"uploads","end":""},{"type":2,"val":"*","end":""}],
    types: placeholder,
  },
  "dashboard.view": {
    methods: ["GET"],
    pattern: "/dashboard",
    tokens: [{"type":0,"val":"dashboard","end":""}],
    types: placeholder,
  },
  "profile.view": {
    methods: ["GET"],
    pattern: "/dashboard/profile",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"profile","end":""}],
    types: placeholder,
  },
  "profile.update": {
    methods: ["PATCH"],
    pattern: "/dashboard/profile",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"profile","end":""}],
    types: placeholder,
  },
  "user.index": {
    methods: ["GET"],
    pattern: "/dashboard/users",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"users","end":""}],
    types: placeholder,
  },
  "user.create": {
    methods: ["GET"],
    pattern: "/dashboard/users/create",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"users","end":""},{"type":0,"val":"create","end":""}],
    types: placeholder,
  },
  "user.edit": {
    methods: ["GET"],
    pattern: "/dashboard/users/edit/:id",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"users","end":""},{"type":0,"val":"edit","end":""},{"type":1,"val":"id","end":""}],
    types: placeholder,
  },
  "user.store": {
    methods: ["POST"],
    pattern: "/dashboard/users/store",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"users","end":""},{"type":0,"val":"store","end":""}],
    types: placeholder,
  },
  "user.update": {
    methods: ["PATCH"],
    pattern: "/dashboard/users/update",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"users","end":""},{"type":0,"val":"update","end":""}],
    types: placeholder,
  },
  "user.destroy": {
    methods: ["DELETE"],
    pattern: "/dashboard/users/delete/:id",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"users","end":""},{"type":0,"val":"delete","end":""},{"type":1,"val":"id","end":""}],
    types: placeholder,
  },
  "user.bulkDestroy": {
    methods: ["DELETE"],
    pattern: "/dashboard/users/bulk-delete",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"users","end":""},{"type":0,"val":"bulk-delete","end":""}],
    types: placeholder,
  },
  "permission.index": {
    methods: ["GET"],
    pattern: "/dashboard/permissions",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"permissions","end":""}],
    types: placeholder,
  },
  "permission.create": {
    methods: ["GET"],
    pattern: "/dashboard/permissions/create",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"permissions","end":""},{"type":0,"val":"create","end":""}],
    types: placeholder,
  },
  "permission.edit": {
    methods: ["GET"],
    pattern: "/dashboard/permissions/edit/:id",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"permissions","end":""},{"type":0,"val":"edit","end":""},{"type":1,"val":"id","end":""}],
    types: placeholder,
  },
  "permission.store": {
    methods: ["POST"],
    pattern: "/dashboard/permissions/store",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"permissions","end":""},{"type":0,"val":"store","end":""}],
    types: placeholder,
  },
  "permission.update": {
    methods: ["PATCH"],
    pattern: "/dashboard/permissions/update",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"permissions","end":""},{"type":0,"val":"update","end":""}],
    types: placeholder,
  },
  "permission.destroy": {
    methods: ["DELETE"],
    pattern: "/dashboard/permissions/delete/:id",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"permissions","end":""},{"type":0,"val":"delete","end":""},{"type":1,"val":"id","end":""}],
    types: placeholder,
  },
  "permission.bulkDestroy": {
    methods: ["DELETE"],
    pattern: "/dashboard/permissions/bulk-delete",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"permissions","end":""},{"type":0,"val":"bulk-delete","end":""}],
    types: placeholder,
  },
  "role.index": {
    methods: ["GET"],
    pattern: "/dashboard/roles",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"roles","end":""}],
    types: placeholder,
  },
  "role.create": {
    methods: ["GET"],
    pattern: "/dashboard/roles/create",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"roles","end":""},{"type":0,"val":"create","end":""}],
    types: placeholder,
  },
  "role.edit": {
    methods: ["GET"],
    pattern: "/dashboard/roles/edit/:id",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"roles","end":""},{"type":0,"val":"edit","end":""},{"type":1,"val":"id","end":""}],
    types: placeholder,
  },
  "role.store": {
    methods: ["POST"],
    pattern: "/dashboard/roles/store",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"roles","end":""},{"type":0,"val":"store","end":""}],
    types: placeholder,
  },
  "role.update": {
    methods: ["PATCH"],
    pattern: "/dashboard/roles/update",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"roles","end":""},{"type":0,"val":"update","end":""}],
    types: placeholder,
  },
  "role.destroy": {
    methods: ["DELETE"],
    pattern: "/dashboard/roles/delete/:id",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"roles","end":""},{"type":0,"val":"delete","end":""},{"type":1,"val":"id","end":""}],
    types: placeholder,
  },
  "role.bulkDestroy": {
    methods: ["DELETE"],
    pattern: "/dashboard/roles/bulk-delete",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"roles","end":""},{"type":0,"val":"bulk-delete","end":""}],
    types: placeholder,
  },
  "media.index": {
    methods: ["GET"],
    pattern: "/dashboard/media",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"media","end":""}],
    types: placeholder,
  },
  "media.create": {
    methods: ["GET"],
    pattern: "/dashboard/media/create",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"media","end":""},{"type":0,"val":"create","end":""}],
    types: placeholder,
  },
  "media.edit": {
    methods: ["GET"],
    pattern: "/dashboard/media/edit/:id",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"media","end":""},{"type":0,"val":"edit","end":""},{"type":1,"val":"id","end":""}],
    types: placeholder,
  },
  "media.store": {
    methods: ["POST"],
    pattern: "/dashboard/media/store",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"media","end":""},{"type":0,"val":"store","end":""}],
    types: placeholder,
  },
  "media.update": {
    methods: ["PATCH"],
    pattern: "/dashboard/media/update",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"media","end":""},{"type":0,"val":"update","end":""}],
    types: placeholder,
  },
  "media.destroy": {
    methods: ["DELETE"],
    pattern: "/dashboard/media/delete/:id",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"media","end":""},{"type":0,"val":"delete","end":""},{"type":1,"val":"id","end":""}],
    types: placeholder,
  },
  "media.bulkDestroy": {
    methods: ["DELETE"],
    pattern: "/dashboard/media/bulk-delete",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"media","end":""},{"type":0,"val":"bulk-delete","end":""}],
    types: placeholder,
  },
  "blog.index": {
    methods: ["GET"],
    pattern: "/dashboard/blogs",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"blogs","end":""}],
    types: placeholder,
  },
  "blog.create": {
    methods: ["GET"],
    pattern: "/dashboard/blogs/create",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"blogs","end":""},{"type":0,"val":"create","end":""}],
    types: placeholder,
  },
  "blog.edit": {
    methods: ["GET"],
    pattern: "/dashboard/blogs/edit/:id",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"blogs","end":""},{"type":0,"val":"edit","end":""},{"type":1,"val":"id","end":""}],
    types: placeholder,
  },
  "blog.store": {
    methods: ["POST"],
    pattern: "/dashboard/blogs/store",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"blogs","end":""},{"type":0,"val":"store","end":""}],
    types: placeholder,
  },
  "blog.update": {
    methods: ["PATCH"],
    pattern: "/dashboard/blogs/update",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"blogs","end":""},{"type":0,"val":"update","end":""}],
    types: placeholder,
  },
  "blog.destroy": {
    methods: ["DELETE"],
    pattern: "/dashboard/blogs/delete/:id",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"blogs","end":""},{"type":0,"val":"delete","end":""},{"type":1,"val":"id","end":""}],
    types: placeholder,
  },
  "blog.bulkDestroy": {
    methods: ["DELETE"],
    pattern: "/dashboard/blogs/bulk-delete",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"blogs","end":""},{"type":0,"val":"bulk-delete","end":""}],
    types: placeholder,
  },
  "blog.rollback": {
    methods: ["POST"],
    pattern: "/dashboard/blogs/rollback",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"blogs","end":""},{"type":0,"val":"rollback","end":""}],
    types: placeholder,
  },
  "blog.rollbackFields": {
    methods: ["POST"],
    pattern: "/dashboard/blogs/rollback-fields",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"blogs","end":""},{"type":0,"val":"rollback-fields","end":""}],
    types: placeholder,
  },
  "activity_log.index": {
    methods: ["GET"],
    pattern: "/dashboard/activity-log",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"activity-log","end":""}],
    types: placeholder,
  },
  "activity_log.clearRange": {
    methods: ["DELETE"],
    pattern: "/dashboard/activity-log/clear-range",
    tokens: [{"type":0,"val":"dashboard","end":""},{"type":0,"val":"activity-log","end":""},{"type":0,"val":"clear-range","end":""}],
    types: placeholder,
  },
  "home": {
    methods: ["GET"],
    pattern: "/",
    tokens: [{"type":0,"val":"/","end":""}],
    types: placeholder,
  },
  "blog": {
    methods: ["GET"],
    pattern: "/blog",
    tokens: [{"type":0,"val":"blog","end":""}],
    types: placeholder,
  },
  "blog.post": {
    methods: ["GET"],
    pattern: "/blog/:segment",
    tokens: [{"type":0,"val":"blog","end":""},{"type":1,"val":"segment","end":""}],
    types: placeholder,
  },
  "api.v1.media.redirect": {
    methods: ["GET"],
    pattern: "/api/v1/public/media/redirect/:id",
    tokens: [{"type":0,"val":"api","end":""},{"type":0,"val":"v1","end":""},{"type":0,"val":"public","end":""},{"type":0,"val":"media","end":""},{"type":0,"val":"redirect","end":""},{"type":1,"val":"id","end":""}],
    types: placeholder,
  },
  "api.v1.public.blog.search": {
    methods: ["GET"],
    pattern: "/api/v1/public/blog/search",
    tokens: [{"type":0,"val":"api","end":""},{"type":0,"val":"v1","end":""},{"type":0,"val":"public","end":""},{"type":0,"val":"blog","end":""},{"type":0,"val":"search","end":""}],
    types: placeholder,
  },
  "api.v1.me.avatar": {
    methods: ["GET"],
    pattern: "/api/v1/me/avatar",
    tokens: [{"type":0,"val":"api","end":""},{"type":0,"val":"v1","end":""},{"type":0,"val":"me","end":""},{"type":0,"val":"avatar","end":""}],
    types: placeholder,
  },
  "api.v1.media.list": {
    methods: ["GET"],
    pattern: "/api/v1/media",
    tokens: [{"type":0,"val":"api","end":""},{"type":0,"val":"v1","end":""},{"type":0,"val":"media","end":""}],
    types: placeholder,
  },
  "api.v1.media.upload": {
    methods: ["POST"],
    pattern: "/api/v1/media",
    tokens: [{"type":0,"val":"api","end":""},{"type":0,"val":"v1","end":""},{"type":0,"val":"media","end":""}],
    types: placeholder,
  },
  "api.v1.media.destroy": {
    methods: ["DELETE"],
    pattern: "/api/v1/media",
    tokens: [{"type":0,"val":"api","end":""},{"type":0,"val":"v1","end":""},{"type":0,"val":"media","end":""}],
    types: placeholder,
  },
  "api.v1.utils.random-password": {
    methods: ["GET"],
    pattern: "/api/v1/utils/random-password",
    tokens: [{"type":0,"val":"api","end":""},{"type":0,"val":"v1","end":""},{"type":0,"val":"utils","end":""},{"type":0,"val":"random-password","end":""}],
    types: placeholder,
  },
  "api.v1.utils.link-metadata": {
    methods: ["GET"],
    pattern: "/api/v1/utils/link-metadata",
    tokens: [{"type":0,"val":"api","end":""},{"type":0,"val":"v1","end":""},{"type":0,"val":"utils","end":""},{"type":0,"val":"link-metadata","end":""}],
    types: placeholder,
  },
  "auth.logout": {
    methods: ["POST"],
    pattern: "/auth/logout",
    tokens: [{"type":0,"val":"auth","end":""},{"type":0,"val":"logout","end":""}],
    types: placeholder,
  },
  "auth.login": {
    methods: ["GET"],
    pattern: "/auth/login",
    tokens: [{"type":0,"val":"auth","end":""},{"type":0,"val":"login","end":""}],
    types: placeholder,
  },
  "auth.login.post": {
    methods: ["POST"],
    pattern: "/auth/login",
    tokens: [{"type":0,"val":"auth","end":""},{"type":0,"val":"login","end":""}],
    types: placeholder,
  },
  "auth.register": {
    methods: ["GET"],
    pattern: "/auth/register",
    tokens: [{"type":0,"val":"auth","end":""},{"type":0,"val":"register","end":""}],
    types: placeholder,
  },
  "auth.register.post": {
    methods: ["POST"],
    pattern: "/auth/register",
    tokens: [{"type":0,"val":"auth","end":""},{"type":0,"val":"register","end":""}],
    types: placeholder,
  },
  "auth.requestResetPassword": {
    methods: ["GET"],
    pattern: "/auth/reset-password",
    tokens: [{"type":0,"val":"auth","end":""},{"type":0,"val":"reset-password","end":""}],
    types: placeholder,
  },
  "auth.requestResetPassword.post": {
    methods: ["POST"],
    pattern: "/auth/reset-password/request",
    tokens: [{"type":0,"val":"auth","end":""},{"type":0,"val":"reset-password","end":""},{"type":0,"val":"request","end":""}],
    types: placeholder,
  },
  "auth.resetPassword": {
    methods: ["GET"],
    pattern: "/auth/reset-password/:token",
    tokens: [{"type":0,"val":"auth","end":""},{"type":0,"val":"reset-password","end":""},{"type":1,"val":"token","end":""}],
    types: placeholder,
  },
  "auth.resetPassword.post": {
    methods: ["POST"],
    pattern: "/auth/reset-password",
    tokens: [{"type":0,"val":"auth","end":""},{"type":0,"val":"reset-password","end":""}],
    types: placeholder,
  },
  "auth.verifyEmail": {
    methods: ["GET"],
    pattern: "/auth/verify-email",
    tokens: [{"type":0,"val":"auth","end":""},{"type":0,"val":"verify-email","end":""}],
    types: placeholder,
  },
  "auth.verifyEmail.verify": {
    methods: ["GET"],
    pattern: "/auth/verify-email/verify/:token",
    tokens: [{"type":0,"val":"auth","end":""},{"type":0,"val":"verify-email","end":""},{"type":0,"val":"verify","end":""},{"type":1,"val":"token","end":""}],
    types: placeholder,
  },
  "auth.verifyEmail.request": {
    methods: ["POST"],
    pattern: "/auth/verify-email/request",
    tokens: [{"type":0,"val":"auth","end":""},{"type":0,"val":"verify-email","end":""},{"type":0,"val":"request","end":""}],
    types: placeholder,
  }
} as const satisfies Record<string, AdonisEndpoint>

export const registry = {
  routes,
  $tree: {} as any,
}
